exports.ROSS_TEAM_LIST_SHEET_NAME = "Teams";
exports.ROSS_MEMBER_LIST_SHEET_NAME = "Members";
exports.ROSS_SPRINTS_SHEET_NAME = "Sprints";
exports.ROSS_TEAM_TEAMPLATE_SHEET_NAME = "Template";
exports.ROSS_STATUS_SHEET_NAME = "Status";

exports.TEAM_STATUS_ACTIVE = 1;
exports.TEAM_STATUS_INACTIVE = 0;

exports.STATUS_INACTIVE = -5;
exports.STATUS_UNPLANNED_LEAVE = -4;
exports.STATUS_PLANNED_LEAVE = -3;
exports.STATUS_HOLIDAY = -2;
exports.STATUS_YET_TO_PLAN = -1;
exports.STATUS_AVAILABLE = 0;
exports.STATUS_CHECKED_IN = 1;
exports.STATUS_ACKNOWLEDGED = 2;
exports.VALID_STATUSES = [
  this.STATUS_INACTIVE,
  this.STATUS_UNPLANNED_LEAVE,
  this.STATUS_PLANNED_LEAVE,
  this.STATUS_HOLIDAY,
  this.STATUS_YET_TO_PLAN,
  this.STATUS_AVAILABLE,
  this.STATUS_CHECKED_IN,
  this.STATUS_ACKNOWLEDGED,
]

exports.XL_TTL = 6 * 60 * 60 * 1000; // 6 hours
exports.XM_TTL = 30 * 60 * 1000; // 30 mins
exports.XS_TTL = 15 * 1000; // 15 seconds

exports.STATUS_TO_TEXT_MAP = {
  [this.STATUS_INACTIVE]: "INACTIVE",
  [this.STATUS_UNPLANNED_LEAVE]: "UNPLANNED_LEAVE",
  [this.STATUS_PLANNED_LEAVE]: "PLANNED_LEAVE",
  [this.STATUS_HOLIDAY]: "HOLIDAY",
  [this.STATUS_YET_TO_PLAN]: "YET_TO_PLAN",
  [this.STATUS_AVAILABLE]: "AVAILABLE",
  [this.STATUS_CHECKED_IN]: "CHECKED_IN",
  [this.STATUS_ACKNOWLEDGED]: "ACKNOWLEDGED",
};

exports.ALLOWED_STATUS_TRANSITION = {
  [this.STATUS_INACTIVE]: [
    this.STATUS_HOLIDAY,
    this.STATUS_YET_TO_PLAN,
    this.STATUS_AVAILABLE,
  ],
  [this.STATUS_UNPLANNED_LEAVE]: [],
  [this.STATUS_PLANNED_LEAVE]: [this.STATUS_HOLIDAY],
  [this.STATUS_HOLIDAY]: [],
  [this.STATUS_YET_TO_PLAN]: [
    this.STATUS_AVAILABLE,
    this.STATUS_PLANNED_LEAVE,
    this.STATUS_HOLIDAY,
    this.STATUS_INACTIVE,
    this.STATUS_CHECKED_IN,
    this.STATUS_UNPLANNED_LEAVE,
  ],
  [this.STATUS_AVAILABLE]: [
    this.STATUS_CHECKED_IN,
    this.STATUS_UNPLANNED_LEAVE,
  ],
  [this.STATUS_CHECKED_IN]: [
    this.STATUS_ACKNOWLEDGED,
    this.STATUS_UNPLANNED_LEAVE,
  ],
  [this.STATUS_ACKNOWLEDGED]: [],
};

exports.TEAM_SHEET_FIRST_MEMBER_COLUMN = "C";

exports.TEAMS_HEADERS_NAME = "Name";
exports.TEAMS_HEADERS_CHANNEL = "Channel";
exports.TEAMS_HEADERS_OWNER = "Owner";
exports.TEAMS_HEADERS_LEADER = "Leader";
exports.TEAMS_HEADERS_MEMBERS = "Members";
exports.TEAMS_HEADERS_ACTIVE = "Active";
exports.TEAMS_HEADERS = [
  this.TEAMS_HEADERS_NAME,
  this.TEAMS_HEADERS_CHANNEL,
  this.TEAMS_HEADERS_OWNER,
  this.TEAMS_HEADERS_LEADER,
  this.TEAMS_HEADERS_MEMBERS,
  this.TEAMS_HEADERS_ACTIVE,
];

exports.MEMBERS_HEADERS_EMAIL = "E-mail";
exports.MEMBERS_HEADERS_HANDLE = "Handle";
exports.MEMBERS_HEADERS = [
  this.MEMBERS_HEADERS_EMAIL,
  this.MEMBERS_HEADERS_HANDLE,
];

exports.TEMPLATE_HEADERS_DATE = "Date";
exports.TEMPLATE_HEADERS_DAY = "Day";
exports.TEMPLATE_HEADERS_TESTMEMBER = "TestMember";
exports.TEMPLATE_HEADERS = [
  this.TEMPLATE_HEADERS_DATE,
  this.TEMPLATE_HEADERS_DAY,
  this.TEMPLATE_HEADERS_TESTMEMBER,
];
